.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH paste 1  "paste " 
.SH NAME
paste \- Print a peer\*(Aqs shared clipboard text to stdout
.SH SYNOPSIS
\fBqdrop paste\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print a peer\*(Aqs shared clipboard text to stdout
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
