.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH open 1  "open " 
.SH NAME
open \- Open a URL on a peer
.SH SYNOPSIS
\fBqdrop open\fR [\fB\-\-to\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIURL\fR> 
.SH DESCRIPTION
Open a URL on a peer
.SH OPTIONS
.TP
\fB\-\-to\fR \fI<NAME>\fR
Target peer name
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIURL\fR>
URL to open on the peer
