.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH daemon 1  "daemon " 
.SH NAME
daemon \- Run the qdrop daemon in the foreground
.SH SYNOPSIS
\fBqdrop daemon\fR [\fB\-\-port\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Run the qdrop daemon in the foreground
.SH OPTIONS
.TP
\fB\-\-port\fR \fI<PORT>\fR
Override the listen port from config
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
